FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential

COPY . /dev86
WORKDIR /dev86
RUN make PREFIX=/install
RUN make install PREFIX=/install

FROM ubuntu:20.04 as package
COPY --from=builder /install /install
